ALTER TABLE "widget"
ADD COLUMN "allowedOrigins" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "devMode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "identityVerificationRequired" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "rateLimitPerMinute" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "configRateLimitPerMinute" INTEGER NOT NULL DEFAULT 120;
